apiVersion: v1
kind: PersistentVolume
metadata:
  name: ftp-data
spec:
  capacity:
    storage: 3G
  storageClassName: hostpath
  accessModes:  
    - ReadWriteOnce
  hostPath:
    path: /k8s-volumes/ftp-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ftp-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 3G